export default [ 
    {  
        id: 1,
        img: "./public/assets/classic.jpg", 
        name: "estate",
        phone: "(212) 555-1234",
        email: "estate@gmail.com",
        availability: true,
        rating: 4.8,
    }, 
    { 
        id: 2,
        img: "./public/assets/rural.jpg", 
        name: "bungalow",
        phone: "(342) 009-3567",
        email: "bungalow@gmail.com",
        availability: true,
        rating: 4.9,
    }, 
    { 
        id: 3,
        img: "./public/assets/modern.jpg", 
        name: "modern house",
        phone: "(567) 154-9977",
        email: "modern@gmail.com",
        availability: false,
        rating: 4.5,
    }, 
    { 
        id: 4,
        img: "./public/assets/victorian.jpg", 
        name: "victorian",
        phone: "(245) 099-4553",
        email: "victorian@gmail.com",
        availability: false,
        rating: 4.7,
    },
]